media:
  input: media
  output: /media

content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    filename: "{year}-{month}-{day}-{title}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: language
        label: Language
        type: select
        options:
          values:
            - en
            - ne
            - de
        required: true

      - name: date
        label: Publication Date
        type: date
        required: true

      - name: category
        label: Category
        type: string

      - name: excerpt
        label: Excerpt
        type: text

      - name: featured_image
        label: Featured Image
        type: image

      - name: body
        label: Content
        type: rich-text